'use client'

import { useEffect, useState } from 'react'
import Image from 'next/image'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Clock3, CreditCard, Download, Loader2, QrCode, RotateCcw, ShieldCheck, X } from 'lucide-react'
import { backendApi, getApiError } from '@/lib/api'
import toast from 'react-hot-toast'

type Subscription = { plan?: string; subscriptionStatus?: string; trialExpired?: boolean; trialDaysRemaining?: number | null; trialEndsAt?: string; usage?: { users?: number; aiMessages?: number; documents?: number } }
type Payment = { _id: string; amount: number; currency: string; status: string; paidAt?: string; createdAt?: string; hostedInvoiceUrl?: string }
type Plan = 'pro' | 'business'

export default function BillingPage() {
  const [subscription,setSubscription]=useState<Subscription>()
  const [payments,setPayments]=useState<Payment[]>([])
  const [loading,setLoading]=useState(true)
  const [processing,setProcessing]=useState(false)
  const [selectedPlan,setSelectedPlan]=useState<Plan | null>(null)
  const [upiPlan,setUpiPlan]=useState<Plan | null>(null)
  const [upiExpiresAt,setUpiExpiresAt]=useState(0)
  const [remainingSeconds,setRemainingSeconds]=useState(120)
  useEffect(()=>{ Promise.all([backendApi.subscription(),backendApi.payments()]).then(([s,p])=>{setSubscription(s.data.data);setPayments(p.data.data)}).catch(e=>toast.error(getApiError(e,'Could not load billing'))).finally(()=>setLoading(false)) },[])
  useEffect(()=>{
    if(!upiPlan||!upiExpiresAt)return
    const update=()=>setRemainingSeconds(Math.max(0,Math.ceil((upiExpiresAt-Date.now())/1000)))
    update()
    const interval=window.setInterval(update,1000)
    return()=>window.clearInterval(interval)
  },[upiPlan,upiExpiresAt])
  const loadCheckout=()=>new Promise<void>((resolve,reject)=>{if((window as any).Razorpay)return resolve();const script=document.createElement('script');script.src='https://checkout.razorpay.com/v1/checkout.js';script.onload=()=>resolve();script.onerror=()=>reject(new Error('Could not load Razorpay Checkout'));document.head.appendChild(script)})
  const checkout=async(plan:Plan)=>{setProcessing(true);setSelectedPlan(null);try{await loadCheckout();const config=(await backendApi.createSubscription(plan)).data.data;const razorpay=new (window as any).Razorpay({key:config.keyId,subscription_id:config.subscriptionId,name:config.name,description:config.description,theme:{color:'#2563eb'},config:{display:{blocks:{preferred:{name:'Pay using a card',instruments:[{method:'card'}]}},sequence:['block.preferred'],preferences:{show_default_blocks:false}}},modal:{ondismiss:()=>setProcessing(false)},handler:async(response:{razorpay_payment_id:string;razorpay_subscription_id:string;razorpay_signature:string})=>{try{await backendApi.verifyPayment(response);const [s,p]=await Promise.all([backendApi.subscription(),backendApi.payments()]);setSubscription(s.data.data);setPayments(p.data.data);toast.success('Subscription activated')}catch(error){toast.error(getApiError(error,'Payment verification failed'))}finally{setProcessing(false)}}});razorpay.on('payment.failed',(response:any)=>{toast.error(response.error?.description||'Payment failed');setProcessing(false)});razorpay.open()}catch(e){toast.error(getApiError(e,'Checkout is unavailable'));setProcessing(false)}}
  const showUpiQr=(plan:Plan)=>{setSelectedPlan(null);setUpiPlan(plan);setRemainingSeconds(120);setUpiExpiresAt(Date.now()+120_000)}
  const retryUpi=()=>{setRemainingSeconds(120);setUpiExpiresAt(Date.now()+120_000)}
  const timer=`${String(Math.floor(remainingSeconds/60)).padStart(2,'0')}:${String(remainingSeconds%60).padStart(2,'0')}`
  if(loading)return <div className="flex justify-center p-16"><Loader2 className="animate-spin"/></div>
  return <div className="max-w-4xl space-y-8"><div><h1 className="text-3xl font-bold">Billing</h1><p className="text-muted-foreground">Subscriptions and payments powered by Razorpay</p></div>
    <Card><CardHeader><CardTitle className="capitalize">{subscription?.plan || 'Free'} plan</CardTitle><CardDescription>{subscription?.plan === 'free' ? (subscription.trialExpired ? 'Your 15-day free trial has ended' : `${subscription.trialDaysRemaining ?? 0} day${subscription.trialDaysRemaining === 1 ? '' : 's'} remaining in your free trial`) : `Status: ${subscription?.subscriptionStatus || 'none'}`}</CardDescription></CardHeader><CardContent><div className="flex flex-wrap gap-3"><Button disabled={processing} onClick={()=>setSelectedPlan('pro')}>{processing?'Opening checkout...':'Upgrade to Pro'}</Button><Button disabled={processing} variant="outline" onClick={()=>setSelectedPlan('business')}>Choose Business</Button></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{Object.entries(subscription?.usage||{}).map(([key,value])=><div key={key} className="rounded-lg bg-muted p-4"><div className="text-2xl font-bold">{value}</div><div className="text-sm capitalize text-muted-foreground">{key}</div></div>)}</div></CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><CreditCard className="h-5 w-5"/>Payment history</CardTitle><CardDescription>Payments verified by the backend and Razorpay webhooks</CardDescription></CardHeader><CardContent>{payments.length===0?<p className="py-8 text-center text-muted-foreground">No payments recorded yet.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b"><th className="p-3 text-left">Date</th><th className="p-3 text-left">Amount</th><th className="p-3 text-left">Status</th><th className="p-3 text-left">Invoice</th></tr></thead><tbody>{payments.map(payment=><tr key={payment._id} className="border-b"><td className="p-3">{new Date(payment.paidAt||payment.createdAt||Date.now()).toLocaleDateString()}</td><td className="p-3 font-medium">{new Intl.NumberFormat(undefined,{style:'currency',currency:(payment.currency||'INR').toUpperCase()}).format(payment.amount/100)}</td><td className="p-3 capitalize">{payment.status}</td><td className="p-3">{payment.hostedInvoiceUrl?<Button variant="ghost" size="sm" onClick={()=>window.open(payment.hostedInvoiceUrl,'_blank')}><Download className="mr-2 h-4 w-4"/>Open</Button>:'—'}</td></tr>)}</tbody></table></div>}</CardContent></Card>
    {selectedPlan&&<div role="dialog" aria-modal="true" aria-labelledby="payment-method-title" className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4 backdrop-blur-sm" onMouseDown={event=>{if(event.target===event.currentTarget)setSelectedPlan(null)}}><div className="w-full max-w-lg rounded-2xl border bg-background p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="payment-method-title" className="text-xl font-semibold">Choose payment method</h2><p className="mt-1 text-sm text-muted-foreground">Upgrade to the <span className="font-medium capitalize text-foreground">{selectedPlan}</span> plan.</p></div><button type="button" onClick={()=>setSelectedPlan(null)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Close payment options"><X className="h-5 w-5"/></button></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>showUpiQr(selectedPlan)} className="group rounded-xl border p-5 text-left transition hover:border-primary hover:bg-primary/5 focus:outline-none focus:ring-2 focus:ring-primary"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-100 text-emerald-700"><QrCode className="h-6 w-6"/></span><span className="mt-4 block font-semibold">UPI</span><span className="mt-1 block text-sm leading-5 text-muted-foreground">Display the QR code and pay using any UPI app.</span></button><button type="button" onClick={()=>checkout(selectedPlan)} className="group rounded-xl border p-5 text-left transition hover:border-primary hover:bg-primary/5 focus:outline-none focus:ring-2 focus:ring-primary"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-100 text-blue-700"><CreditCard className="h-6 w-6"/></span><span className="mt-4 block font-semibold">Credit or debit card</span><span className="mt-1 block text-sm leading-5 text-muted-foreground">Pay securely using your Visa, Mastercard, or RuPay card.</span></button></div><p className="mt-5 flex items-center justify-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 text-emerald-600"/> Choose your preferred secure payment method.</p></div></div>}
    {upiPlan&&<div role="dialog" aria-modal="true" aria-labelledby="upi-payment-title" className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-black/60 p-3 backdrop-blur-sm" onMouseDown={event=>{if(event.target===event.currentTarget)setUpiPlan(null)}}><div className="my-3 w-full max-w-sm rounded-2xl border bg-background p-4 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="upi-payment-title" className="text-lg font-semibold">Pay using UPI</h2><p className="mt-1 text-xs text-muted-foreground">Scan to upgrade to the <span className="font-medium capitalize text-foreground">{upiPlan}</span> plan.</p></div><button type="button" onClick={()=>setUpiPlan(null)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Close UPI QR code"><X className="h-5 w-5"/></button></div>{remainingSeconds>0?<><div className="mt-3 flex items-center justify-between rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300"><span className="flex items-center gap-2"><Clock3 className="h-4 w-4"/>QR expires in</span><strong className="font-mono text-base">{timer}</strong></div><div className="mt-3 overflow-hidden rounded-xl border bg-[#f3f6ff] p-2"><Image src="/upi-qr.png" alt="UPI QR code for Karan Talekar" width={1080} height={1600} priority className="mx-auto h-auto max-h-[42vh] w-auto rounded-lg object-contain sm:max-h-[46vh]"/></div><div className="mt-3 rounded-xl bg-muted px-3 py-2 text-center"><p className="text-[11px] text-muted-foreground">UPI ID</p><p className="mt-0.5 break-all font-mono text-xs font-semibold">karantalekar04-1@okaxis</p></div><p className="mt-3 text-center text-[11px] leading-4 text-muted-foreground">After completing the payment, keep the UPI transaction ID for payment verification.</p></>:<div className="mt-4 rounded-xl border border-dashed bg-muted/50 px-5 py-9 text-center"><QrCode className="mx-auto h-9 w-9 text-muted-foreground"/><h3 className="mt-3 font-semibold">QR code expired</h3><p className="mt-1 text-xs text-muted-foreground">Start a new two-minute payment session to try again.</p><Button onClick={retryUpi} size="sm" className="mt-4"><RotateCcw className="mr-2 h-4 w-4"/>Retry again</Button></div>}</div></div>}
  </div>
}
