'use client'

import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

type Count = { _id: string; count: number }
interface Props { view: 'overview' | 'crm' | 'projects'; crm: { byStatus: Count[]; leadsByMonth: Count[]; customersByMonth: Count[] }; projects: { byStatus: Count[]; tasksByStatus: Count[]; projectsByMonth: Count[]; tasksByMonth: Count[] } }
const colors = ['#7c3aed','#ea580c','#059669','#2563eb','#db2777','#ca8a04']
const tooltipStyle = { backgroundColor: 'rgb(var(--color-card) / 1)', border: '1px solid rgb(var(--color-border) / 1)', borderRadius: 8 }
function monthRows(crm: Props['crm'], projects: Props['projects']) { return Array.from({length: 6}, (_, index) => { const date = new Date(); date.setMonth(date.getMonth() - (5 - index)); const key = `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`; const get = (items: Count[]) => items.find(item => item._id === key)?.count || 0; return { month: date.toLocaleString('en',{month:'short'}), leads: get(crm.leadsByMonth), customers: get(crm.customersByMonth), projects: get(projects.projectsByMonth), tasks: get(projects.tasksByMonth) } }) }
const labels = (items: Count[]) => items.map(item => ({ name: item._id.replaceAll('_',' '), count: item.count }))

export function AnalyticsVisuals({ view, crm, projects }: Props) {
  const trend = monthRows(crm, projects); const crmStatus = labels(crm.byStatus); const projectStatus = labels(projects.byStatus); const taskStatus = labels(projects.tasksByStatus)
  return <div className="grid gap-6 lg:grid-cols-2">
    {(view === 'overview') && <Card className="lg:col-span-2"><CardHeader><CardTitle>Six-month Activity Trend</CardTitle><CardDescription>New leads, customers, projects, and tasks from live records</CardDescription></CardHeader><CardContent><ResponsiveContainer width="100%" height={340}><AreaChart data={trend}><defs>{[['leads','#7c3aed'],['customers','#ea580c'],['projects','#059669'],['tasks','#2563eb']].map(([key,color]) => <linearGradient key={key} id={key} x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={color} stopOpacity={0.45}/><stop offset="95%" stopColor={color} stopOpacity={0}/></linearGradient>)}</defs><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis allowDecimals={false}/><Tooltip contentStyle={tooltipStyle}/><Legend/>{['leads','customers','projects','tasks'].map((key,index) => <Area key={key} type="monotone" dataKey={key} stroke={colors[index]} fill={`url(#${key})`} strokeWidth={2}/>)}</AreaChart></ResponsiveContainer></CardContent></Card>}
    {(view === 'overview' || view === 'crm') && <Card><CardHeader><CardTitle>Lead Pipeline</CardTitle><CardDescription>Leads grouped by current sales status</CardDescription></CardHeader><CardContent>{crmStatus.length ? <ResponsiveContainer width="100%" height={320}><BarChart data={crmStatus}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="count" name="Leads" fill="#7c3aed" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer> : <Empty/>}</CardContent></Card>}
    {(view === 'overview' || view === 'projects') && <Card><CardHeader><CardTitle>Project Distribution</CardTitle><CardDescription>Share of projects at each stage</CardDescription></CardHeader><CardContent>{projectStatus.length ? <ResponsiveContainer width="100%" height={320}><PieChart><Pie data={projectStatus} dataKey="count" nameKey="name" innerRadius={65} outerRadius={105} paddingAngle={3} label>{projectStatus.map((_, index) => <Cell key={index} fill={colors[index % colors.length]}/>)}</Pie><Tooltip contentStyle={tooltipStyle}/><Legend/></PieChart></ResponsiveContainer> : <Empty/>}</CardContent></Card>}
    {(view === 'projects') && <Card className="lg:col-span-2"><CardHeader><CardTitle>Task Workload</CardTitle><CardDescription>Tasks grouped by workflow stage</CardDescription></CardHeader><CardContent>{taskStatus.length ? <ResponsiveContainer width="100%" height={340}><BarChart data={taskStatus} layout="vertical"><CartesianGrid strokeDasharray="3 3"/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={100}/><Tooltip contentStyle={tooltipStyle}/><Bar dataKey="count" name="Tasks" fill="#2563eb" radius={[0,6,6,0]}/></BarChart></ResponsiveContainer> : <Empty/>}</CardContent></Card>}
  </div>
}
function Empty() { return <div className="flex h-[320px] items-center justify-center text-muted-foreground">No data available yet.</div> }
